### ISSUE TITLE
Question of GPU Memory 

### ISSUE THREAD

**Issue by loneboy070** [Edward-Sun/DIFUSCO#10]
Hi Edward,

First of all, I appreciate to your contribution of this area. Recently, I read your paper diligently and try to reproduce your algorithm. 

During this, I found that my gpus can not support enough memory size. 
I tried to reproduce the code for the case of TSP1000 with RTX 3090 (gpu memory: 24 gb) or A40 (gpu memory: 48gb). (V100 Tesla has 32gb gpu memory size)

For both cases, the gpu memory can not support the commented batch size 8 for each gpu. (1 for RTX 3090, 3 for A40 in my cases)

As my understanding, there are 12 layers with 256 nodes per layer, and fp16 option is not enabled in the reproduce code. 
Is my understanding for the reproduction is correct?

Best regards,
Hyungseok Song.

**Comment by Edward-Sun** [comment]
Hi Hyungseok,

Yes, we didn't use fp16 but we used `--use_activation_checkpoint`. I think the [provided script](https://github.com/Edward-Sun/DIFUSCO/blob/main/reproducing_scripts.md#training-on-tsp1000) should work with A40 (48 Gb GPU memory).

**Comment by loneboy070** [comment]
Thanks for your comment to use --use_activation_checkpoint. Now, it works well. :)
