### ISSUE TITLE
Conda environment failure related to pyconcorde and Python 3.8

### ISSUE THREAD

**Issue by Victorvhrn** [Edward-Sun/DIFUSCO#12]
I'm using conda version 24.1.2 in Ubuntu 22.04. When I attempt the command: 

`conda env create -f environment.yml`

I get the following error, with the full output attached:

ERROR: Could not find a version that satisfies the requirement pyconcorde==0.1.0 (from versions: none)
ERROR: No matching distribution found for pyconcorde==0.1.0

I don't understand much about anaconda, but it seems the environment has Python3.7 but  pyconcorde requires python 3.8. If pyconcorde is taken from [here](https://github.com/jvkersch/pyconcorde), the README states that Python 3.7 is enough. Is that a problem with pyconcorde or some other module? Can someone please help with the best fix, so I can run the code?

[output_conda_env_difusco.txt](https://github.com/Edward-Sun/DIFUSCO/files/15243031/output_conda_env_difusco.txt)

**Comment by bokveizen** [comment]
I think this is because pyconcorde is not on PyPI.
You can just do 
`
pip install 'pyconcorde @ git+https://github.com/jvkersch/pyconcorde'
`
