### ISSUE TITLE
The download address of the dataset

### ISSUE THREAD

**Issue by AlexAuthor7** [Edward-Sun/DIFUSCO#2]
Hi, I admire your work very much, but I have encountered some troubles when trying to implement the algorithm. I would like to know if you can provide the download address of the data set (tsp500-10000)

**Comment by Edward-Sun** [comment]
Have you checked [https://github.com/Edward-Sun/DIFUSCO/tree/main/data](https://github.com/Edward-Sun/DIFUSCO/tree/main/data)?

**Comment by AlexAuthor7** [comment]
Yes, we checked it. However, due to hardware limitations, it is difficult for us to generate the data of tsp-10000 in a reasonable time.

**Comment by AlexAuthor7** [comment]
> Yes, we checked it. However, due to hardware limitations, it is difficult for us to generate the data of tsp-10000 in a reasonable time.

Yes, we checked it. However, due to hardware limitations, it is difficult for us to generate the data of tsp-10000 in a reasonable time.

**Comment by AlexAuthor7** [comment]
> Have you checked https://github.com/Edward-Sun/DIFUSCO/tree/main/data?

Yes, we checked it. However, due to hardware limitations, it is difficult for us to generate the data of tsp-10000 in a reasonable time.

**Comment by Edward-Sun** [comment]
I see. I just uploaded our training data for TSP. You can check this link: [https://drive.google.com/drive/folders/1ZN6n3RvpZvGEFw-vfYUn2BMaT6BI0tZe?usp=sharing](https://drive.google.com/drive/folders/1ZN6n3RvpZvGEFw-vfYUn2BMaT6BI0tZe?usp=sharing)

**Comment by AlexAuthor7** [comment]
> I see. I just uploaded our training data for TSP. You can check this link: https://drive.google.com/drive/folders/1ZN6n3RvpZvGEFw-vfYUn2BMaT6BI0tZe?usp=sharing

Thank you for your generosity

**Comment by Yishun99** [comment]
Hi @Edward-Sun , can you upload the tspXXX_valid_concorde.txt and tspXXX_test_concorde.txt for fair comparison and reproducing?  Because of the data generation procedure involves randomness. 

Thank you for your generosity.
