### ISSUE TITLE
Code for MCTS.

### ISSUE THREAD

**Issue by yangco-le** [Edward-Sun/DIFUSCO#3]
Hi, authors. This repo is very helpful for my research, but it doesn't seem to include the code for MCTS. This prevents me from reproducing the results of the paper directly. I have tried MCTS code from previous works but failed to reproduce the results in the paper, which I suspect may due to my improper post-processing of the heatmaps. I wonder whether it is possible to include this part of the code in this repo. I sincerely appreciate any help you can provide.

**Comment by Edward-Sun** [comment]
Hi Yang,

Thanks a lot for your interest in our work and sorry for the delayed response. Our paper is just accepted by NeurIPS but I need to work for the ICLR deadline this week. I will update the code of MCTS soon (perhaps next week).

**Comment by xyfffff** [comment]
Hi there, any update?

**Comment by Edward-Sun** [comment]
Hi all, I'm very sorry for the long wait. The MCTS code is [released](https://github.com/Edward-Sun/DIFUSCO/tree/main/tsp_mcts).

@yangco-le @xyfffff

**Comment by xyfffff** [comment]
Thanks a lot!!

**Comment by yangco-le** [comment]
Nice work. Thanks!
