### ISSUE TITLE
Request for Additional Information on Time Metrics and Heatmaps in Tables 1 and 2

### ISSUE THREAD

**Issue by xyfffff** [Edward-Sun/DIFUSCO#5]
Hello Edward,

I am currently reproducing the results presented in your paper, and I have encountered a couple of issues that I'm hoping you can help me with to ensure an accurate comparison with other works.

Firstly, while **Table 1** in the paper provides details on `Length` and `Drop`, there is no mention of the `Time` taken for each dataset. Although **Table 2** includes the `Time`, it is not explicitly divided into the `time taken for generating the Heatmap` and the `time taken for the subsequent search process`. For the sake of a fair comparison with other papers, could you kindly share the `Time` details for **Table 1** and **Table 2**, as well as the breakdown of the time consumed for each part?

Secondly, I appreciate that you have shared the checkpoints, which are immensely helpful. However, to fully reproduce your paper's results, could you also share the **Heatmap**s generated for the datasets in **Tables 1 and 2**? Access to these Heatmaps would be incredibly valuable for my reproducing.

Thank you for your time and assistance, and for your contributions to the field. I look forward to your response.

Best regards,
Yifan

**Comment by Edward-Sun** [comment]
Hi Yifan,

About time in Table 1, please refer to FAQ A.4 in our [camera-ready version of the paper](https://openreview.net/attachment?id=JV8Ff0lgVV&name=pdf).

About the time taken for each stage (I assume you are referring to the MCTS results), I think you can approximate the neural network time by the greedy decoding time, and MCTS is the total time subtract that.

Currently, we don't have a plan to share the heatmap checkpoints, as they are usually super large, especially for TSP-10000 instances. But I think you can easily reproduce them by just running our inference code with the provided checkpoints.

Thanks

**Comment by xyfffff** [comment]
Thank you very much for your assistance. It's been invaluable in advancing my research.
