### ISSUE TITLE
Questions about Table 1

### ISSUE THREAD

**Issue by xyfffff** [Edward-Sun/DIFUSCO#6]
Hello Edward,

I saw that in `Table 1` your model achieved a negative drop, e.g., `-0.01%` for TSP-50 and `-0.01%` for TSP-100, taking Concorde as the baseline. But Concorde is the exact solver, right? So how could any model achieve a better solution than Concorde? Is the negative drop due to some round-off errors?

Best regards,
Yifan

**Comment by Edward-Sun** [comment]
Hi Yifan,

About results in Table 1, please refer to FAQ A.4 in our [camera-ready version of the paper](https://openreview.net/attachment?id=JV8Ff0lgVV&name=pdf).

Yes. We assume this is because of some rounding errors of the integer input of Concorde.

Thanks
