### ISSUE TITLE
Clarification on MCTS Runtime Comparison in Table 2

### ISSUE THREAD

**Issue by xyfffff** [Edward-Sun/DIFUSCO#7]
Hello Edward,

In Table 2, for TSP1000, I noticed that for the DIFUSCO model, the SL+G's runtime is `11.86` minutes, and the SL+MCTS's runtime is `24.47` minutes. It can be estimated that the MCTS component alone takes about `12` minutes. However, when comparing this to the ATT-GCN and DIMES models, which also utilize MCTS, I observed that their total runtime (including both inference and MCTS) is only `4.1` minutes and `6.87` minutes, respectively.

This leads me to question the fairness of this comparison. The MCTS runtime for DIFUSCO seems significantly longer than that for the other two models. Given that providing more time to MCTS generally yields higher quality solutions, I am curious whether this difference in allocated runtime might affect the fairness of the comparison.

Could you please clarify whether the runtime for MCTS is consistent across these models, or if there are other factors contributing to this apparent discrepancy?

Thank you for your attention to this matter.

Best regards,
Yifan

**Comment by xyfffff** [comment]
Oh, I just realized a fact that I previously overlooked. It appears that the MCTS runtimes for ATT-GCN and DIMES in your table were conducted under a `64-thread` setup, as per the hardware specifications mentioned in the DIMES paper. However, it seems that MCTS in your implementation was not executed with 64 threads.

After reviewing your MCTS code, I noticed that the default thread count is set to 16. Therefore, I would like to confirm: were the MCTS algorithms for TSP500, TSP1000, and TSP10000 run and timed under a `16-thread` setup in your experiments?

This information would help in understanding the runtime comparison more accurately.

Thank you for your clarification.

**Comment by Edward-Sun** [comment]
Hi Yifan, for your first question, the results of other baselines are taken from the corresponding publications, and may use different hardware, so the runtime may not be directly comparable.

For your second question, the code we released is the code that is used to produce the results in the paper. So the results are obtained with a `16-thread` setup.
