### ISSUE TITLE
--save_numpy_heatmap and MCTS Evaluation

### ISSUE THREAD

**Issue by xyfffff** [Edward-Sun/DIFUSCO#8]
Hello Edward,

I'm encountering a problem when using the `--save_numpy_heatmap` flag in the evaluate script, especially when trying to solve with MCTS. Here's a detailed description of the issues I'm facing:

1. **For `solve-500.sh`:** When I run this script, it throws a ValueError during the reshaping of the adjacency matrix. The error message is:

> adj_matrix = np.load(file_name).reshape(num_nodes, num_nodes)
ValueError: cannot reshape array of size 25000 into shape (500,500)

This suggests that the numpy array size doesn't match the expected dimensions for a 500-node problem.

2. **For `solve-1000.sh`:** A different error occurs in the `convert_numpy_to_txt.py` script:

> File "convert_numpy_to_txt.py", line 22, in main
adj_matrix = adj_matrix + 0.01 * (1.0 - dists)
ValueError: operands could not be broadcast together with shapes (100000,) (1000,1000)

This error seems to indicate a mismatch in the dimensions of the operands for matrix operations, implying an issue with the shape of the saved numpy array.

Upon reviewing the `plt_tsp_model.py` script, I suspect that the saved `adj_matrix` might be a sparse matrix, which could be causing these shape inconsistencies. Could you please help clarify if this is the case, and if so, suggest a way to correctly reshape or convert the matrix for proper usage in the scripts mentioned above?

Thank you for your assistance and for your work on this project.

Best regards,
Yifan

**Comment by Edward-Sun** [comment]
Hi Yifan,

Yes, the heatmaps for large TSP problems are sparse. For example, each node in TSP-500 only has 50 neighborhoods, so the whole graph has 500 x 50 = 25000 edges. They can be converted to a dense heatmap with [scipy.sparse.coo_matrix](https://github.com/Edward-Sun/DIFUSCO/blob/8e81283bc517e3b883e10f6544646fd5ffa6f6bc/difusco/utils/tsp_utils.py#L110).

For TSP-1000, this seems to be the same issue, as the `sparse_factor` in TSP-1000 is 100.
