### ISSUE TITLE
Discrepancies in Reproducing Results for TSP Diffusion Method

### ISSUE THREAD

**Issue by xyfffff** [Edward-Sun/DIFUSCO#9]
Hi Edward,

I hope this message finds you well. I'm reaching out regarding your recent paper on the diffusion method for TSP. First and foremost, I'd like to commend you on your innovative approach and the clarity of your paper. Your work has certainly contributed significantly to this field.

I've been attempting to replicate your results using the scripts provided in your GitHub repository. While I've been able to closely match most of your reported outcomes, there are a few discrepancies I've encountered, especially in the larger TSP instances.

For example, in the TSP-500 and TSP-1000 instances, my results were very close to yours:
- SL+MCTS for TSP-500: Your result - 16.63, My result - 16.64
- SL+MCTS for TSP-1000: Your result - 23.39, My result - 23.41
- SL+S+2-opt for TSP-500: Your result - 16.65, My result - 16.70
- SL+S+2-opt for TSP-1000: Your result - 23.45, My result - 23.42
- SL+S+2-opt for TSP-10000: Your result - 73.89, My result - 73.83

These variations are minor and within acceptable ranges. However, I am facing a significant challenge with the SL+MCTS method for TSP-10000. According to your paper, the result for this instance is 73.62. In contrast, my replication yields a result of 73.92, which not only deviates notably from your reported outcome but is also less effective than the SL+S+2-opt method, which is unexpected. Despite using the provided script and following the instructions accurately, my results diverge notably from those in your paper. This is quite perplexing, and I'm unsure what might be causing this discrepancy.

For reference, here's the exact command I used:
`python -u difusco/train.py --task "tsp" --wandb_logger_name "tsp_diffusion_graph_categorical_tsp10000" --diffusion_type "categorical" --do_test --learning_rate 0.0002 --weight_decay 0.0001 --lr_scheduler "cosine-decay" --storage_path "./data" --training_split "tsp10000_test_concorde.txt" --validation_split "tsp10000_test_concorde.txt" --test_split "tsp10000_test_concorde.txt" --sparse_factor 100 --batch_size 1 --num_epochs 25 --validation_examples 8 --inference_schedule "cosine" --inference_diffusion_steps 50 --ckpt_path "./checkpoint/tsp10000_categorical.ckpt" --resume_weight_only --save_numpy_heatmap
`

I then used the provided MCTS code for post-processing, but the results were not as expected. Despite multiple attempts at rerunning the scripts for generating the heatmap and conducting the MCTS search, my results are consistently not comparable to those presented in your paper.

I would greatly appreciate any insights or suggestions you might have that could help me align my results more closely with those reported in your paper. Your guidance in this matter would be invaluable.

Thank you for your time and consideration, and I look forward to your response.

Best regards,
Yifan

**Comment by xyfffff** [comment]
It's quite strange that now I rerun the script and got the result of SL+MCTS for TSP-500 to be 16.62 (which is better than the result reported in the paper...), and the result of SL+MCTS for TSP-10000 to be 73.76 (which is better than my previous result but still worse than the result in the paper...).

**Comment by Edward-Sun** [comment]
Hi @xyfffff ,

Thanks a lot for reporting the issue. I checked the log and just realized the tsp-10000-mcts results are obtained by applying a 2-OPT process before feeding to the MCTS solver. Please check the updated code:

https://github.com/Edward-Sun/DIFUSCO/blob/main/tsp_mcts/solve-10000.sh

https://github.com/Edward-Sun/DIFUSCO/blob/main/tsp_mcts/convert_numpy_with_2opt.py

**Comment by xyfffff** [comment]
Dear Edward,

I hope this message finds you well. First and foremost, I would like to express my gratitude for your contributions to the field and for sharing your code on GitHub. It's a valuable resource for the community.

I've recently tried running your updated script and would like to share some observations and seek your assistance for a few issues I encountered:

1. Performance Concerns:
- For TSP-10000, the script seems quite time-consuming during the merge process and the 2-opt application. It takes approximately 33 seconds for Union find and 205 seconds for 2-opt per instance. This duration exceeds the time reported in the original paper's results, leading to longer overall computation times for the model.
2. Issue with 2-opt Implementation:
- After applying 2-opt, I observed a notable decrease in performance. Specifically, the average MCTS length increased to 79.39, which is significantly worse than the result before the 2-opt modification.

Additionally, I encountered some minor issues while trying to run the updated code directly:
- Imports Adjustment:
```
import sys
sys.path.append('../difusco')

from utils.tsp_utils import TSPEvaluator
from utils.cython_merge.cython_merge import merge_cython
```
- Initialization of `solved_costs`:
It appears that `solved_costs = []` needs to be defined in the main function.
- Misplaced `TSPEvaluator`:
The `TSPEvaluator` is defined in tsp_utils.py rather than `TSP_2opt`.
- Formatting in Main Function:
There seem to be some inaccuracies with the indentations in the main function.

I highly appreciate your efforts and would be immensely grateful for any guidance or suggestions you could provide to help me accurately replicate your results.

Thank you for your time and assistance.

Best regards,
Yifan

**Comment by Edward-Sun** [comment]
Hi @xyfffff ,

Thank you for closely following our work. I found my notes wrote some like

```
# Mean (PDM + 0.01 * dist scores): 73.8229338125
# Mean (PDM + 2OPT + 0.01 * dist scores): 73.621185875
```

So I'm sure the final results are reported with 2-opt. I will check the code again soon.
